### ISSUE TITLE
Failure to build wheels for piton 

### ISSUE THREAD

**Issue by scottfleming** [som-shahlab/piton#34]
## Describe the bug
After following the install instructions in the `README`, I get an error when running `pip install -e .` from within the cloned `piton` directory.

## Steps to reproduce the bug
```bash
conda create -n PITON_ENV python=3.10 bazel=5 clangxx=14 -c conda-forge
conda activate PITON_ENV
git clone https://github.com/som-shahlab/piton.git
cd piton
piton install -e .
```

## Expected results
Expected a clean install.

## Actual results
```
Obtaining file:///local-scratch/nigam/projects/scottyf/piton
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting scikit-learn>=0.24
  Using cached scikit_learn-1.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.5 MB)
Collecting numpy>=1.22
  Using cached numpy-1.23.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Collecting scipy>=1.6
  Using cached scipy-1.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.7 MB)
Collecting zstandard>=0.18
  Using cached zstandard-0.19.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)
Collecting tqdm>=4.60.0
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting joblib>=1.1.1
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Building wheels for collected packages: piton
  Building editable for piton (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for piton (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [83 lines of output]
      running editable_wheel
      creating /tmp/pip-wheel-abf14yrk/.tmp-ad7458up/piton.egg-info
      writing /tmp/pip-wheel-abf14yrk/.tmp-ad7458up/piton.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-abf14yrk/.tmp-ad7458up/piton.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-wheel-abf14yrk/.tmp-ad7458up/piton.egg-info/entry_points.txt
      writing requirements to /tmp/pip-wheel-abf14yrk/.tmp-ad7458up/piton.egg-info/requires.txt
      writing top-level names to /tmp/pip-wheel-abf14yrk/.tmp-ad7458up/piton.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-abf14yrk/.tmp-ad7458up/piton.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-wheel-abf14yrk/.tmp-ad7458up/piton.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-abf14yrk/.tmp-ad7458up/piton-0.1.0.dist-info'
      creating /tmp/pip-wheel-abf14yrk/.tmp-ad7458up/piton-0.1.0.dist-info/WHEEL
      running build_py
      running build_ext
      WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
      Loading:
      Loading: 1 packages loaded
      Analyzing: target //:extension.so (2 packages loaded, 0 targets configured)
      DEBUG: Rule 'pybind11' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "69cd45ac4a0237a53ca56c1dd50431c564affe0006c5be4d9d1a1d4c7c51a9ee"
      DEBUG: Repository pybind11 instantiated at:
        /local-scratch/nigam/projects/scottyf/piton/native/WORKSPACE:60:13: in <toplevel>
      Repository rule http_archive defined at:
        /home/scottyf/miniconda/envs/piton/share/bazel/10afe504e153b5c84d979839799701ed/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
      INFO: non-existent distdir /local-scratch/nigam/distdir:
      Analyzing: target //:extension.so (5 packages loaded, 259 targets configured)
      Analyzing: target //:extension.so (5 packages loaded, 259 targets configured)
      Analyzing: target //:extension.so (5 packages loaded, 259 targets configured)
      Analyzing: target //:extension.so (5 packages loaded, 259 targets configured)
      Analyzing: target //:extension.so (5 packages loaded, 259 targets configured)
      INFO: Repository boost instantiated at:
        /local-scratch/nigam/projects/scottyf/piton/native/WORKSPACE:172:11: in <toplevel>
        /home/scottyf/miniconda/envs/piton/share/bazel/10afe504e153b5c84d979839799701ed/external/com_github_nelhage_rules_boost/boost/boost.bzl:208:10: in boost_deps
        /home/scottyf/miniconda/envs/piton/share/bazel/10afe504e153b5c84d979839799701ed/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
      Repository rule http_archive defined at:
        /home/scottyf/miniconda/envs/piton/share/bazel/10afe504e153b5c84d979839799701ed/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
      WARNING: Download from https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz failed: class java.io.IOException Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
      ERROR: An error occurred during the fetch of repository 'boost':
         Traceback (most recent call last):
          File "/home/scottyf/miniconda/envs/piton/share/bazel/10afe504e153b5c84d979839799701ed/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
                  download_info = ctx.download_and_extract(
      Error in download_and_extract: java.io.IOException: Error downloading [https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz] to /home/scottyf/miniconda/envs/piton/share/bazel/10afe504e153b5c84d979839799701ed/external/boost/temp5597963431990635805/boost_1_80_0.tar.gz: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
      ERROR: /local-scratch/nigam/projects/scottyf/piton/native/WORKSPACE:172:11: fetching http_archive rule //external:boost: Traceback (most recent call last):
          File "/home/scottyf/miniconda/envs/piton/share/bazel/10afe504e153b5c84d979839799701ed/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
                  download_info = ctx.download_and_extract(
      Error in download_and_extract: java.io.IOException: Error downloading [https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz] to /home/scottyf/miniconda/envs/piton/share/bazel/10afe504e153b5c84d979839799701ed/external/boost/temp5597963431990635805/boost_1_80_0.tar.gz: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
      ERROR: /local-scratch/nigam/projects/scottyf/piton/native/BUILD:208:11: //:join_csvs depends on @boost//:filesystem in repository @boost which failed to fetch. no such package '@boost//': java.io.IOException: Error downloading [https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz] to /home/scottyf/miniconda/envs/piton/share/bazel/10afe504e153b5c84d979839799701ed/external/boost/temp5597963431990635805/boost_1_80_0.tar.gz: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
      ERROR: Analysis of target '//:extension.so' failed; build aborted:
      INFO: Elapsed time: 13.583s
      INFO: 0 processes.
      FAILED: Build did NOT complete successfully (5 packages loaded, 259 targets configured)
      FAILED: Build did NOT complete successfully (5 packages loaded, 259 targets configured)
      Traceback (most recent call last):
        File "/tmp/pip-build-env-p0sikudl/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 140, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-p0sikudl/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 330, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-p0sikudl/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 261, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-p0sikudl/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 288, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-p0sikudl/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-p0sikudl/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-p0sikudl/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-p0sikudl/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-p0sikudl/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "<string>", line 52, in build_extensions
        File "/home/scottyf/miniconda/envs/piton/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', 'extension.so', '--distdir', '/local-scratch/nigam/distdir:']' returned non-zero exit status 1.
      error: Support for editable installs via PEP 660 was recently introduced
      in `setuptools`. If you are seeing this error, please report to:
      
      https://github.com/pypa/setuptools/issues
      
      Meanwhile you can try the legacy behavior by setting an
      environment variable and trying to install again:
      
      SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for piton
Failed to build piton
ERROR: Could not build wheels for piton, which is required to install pyproject.toml-based projects
```

Note that setting `SETUPTOOLS_ENABLE_FEATURES` as suggested does not work.

## Environment info

- Platform: Nero (Linux version 4.15.0-142-generic)

**Comment by scottfleming** [comment]
Realized that there was a typo when I tried to set `DISTDIR=/local-scratch/nigam/distdir`, but thought I'd keep this as an issue in case anyone else forgets to set their `DISTDIR` appropriately.
