### ISSUE TITLE
"storage buckets create" needs permission for new user

### ISSUE THREAD

**Issue by ZepengHuo** [som-shahlab/piton#78]
When running the 'download_bigquery.py', I got error (where `os.environ['GOOGLE_APPLICATION_CREDENTIALS']` has my credential alrady):

> Make sure to run "gcloud auth application-default login" before running this command
/home/zphuo/.conda/envs/PITON_ENV/lib/python3.10/site-packages/google/auth/_default.py:83: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
/home/zphuo/.conda/envs/PITON_ENV/lib/python3.10/site-packages/google/auth/_default.py:83: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
Traceback (most recent call last):
  File "/local-scratch/nigam/projects/zphuo/repos/clinical-text-with-codes-text-featurizers/pe_labels/download_bigquery.py", line 94, in <module>
    bucket = storage_client.create_bucket(bucket, location="us-west2")
  File "/home/zphuo/.conda/envs/PITON_ENV/lib/python3.10/site-packages/google/cloud/storage/client.py", line 948, in create_bucket
    api_response = self._post_resource(
  File "/home/zphuo/.conda/envs/PITON_ENV/lib/python3.10/site-packages/google/cloud/storage/client.py", line 612, in _post_resource
    return self._connection.api_request(
  File "/home/zphuo/.conda/envs/PITON_ENV/lib/python3.10/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/zphuo/.conda/envs/PITON_ENV/lib/python3.10/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/home/zphuo/.conda/envs/PITON_ENV/lib/python3.10/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/home/zphuo/.conda/envs/PITON_ENV/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://storage.googleapis.com/storage/v1/b?project=som-nero-nigam-starr&prettyPrint=false: zphuo@stanford.edu does not have storage.buckets.create access to the Google Cloud project. Permission 'storage.buckets.create' denied on resource (or it may not `exist).`

**Comment by Lalaland** [comment]
You need to request GCP bucket access from Jason.

Also, it's not recommended for each person to download extracts. We pay a cost of $60 or so per download so best to minimize duplicate downloads.
